version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: recauderia_db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
